version: '3.8'

services:

  front:
    image: transcendance:front
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.server == true
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.transcendance-front.loadbalancer.server.port=3000"
        - "traefik.http.routers.transcendance-front.rule=Host(`pong-wars.cyberduck.blog`)"
        - "traefik.http.routers.transcendance-front.entrypoints=websecure"
        - "traefik.http.routers.transcendance-front.priority=1"
        - "traefik.http.routers.transcendance-front.tls=true"
        - "traefik.http.routers.transcendance-front.tls.certresolver=letsencryptresolver"
    networks:
      - net
      - traefik-public

  back:
    image: transcendance:back
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.server == true
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.transcendance-back.loadbalancer.server.port=8080"
        - "traefik.http.routers.transcendance-back.rule=Host(`pong-wars.cyberduck.blog`) && (PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/socket.io`))"
        - "traefik.http.routers.transcendance-back.entrypoints=websecure"
        - "traefik.http.routers.transcendance-back.priority=2"
        - "traefik.http.routers.transcendance-back.tls=true"
        - "traefik.http.routers.transcendance-back.tls.certresolver=letsencryptresolver"
    networks:
      - net
      - traefik-public
    volumes:
      - type: volume
        source: back-avatars
        target: /usr/src/app/avatars

  postgres:
    image: postgres:latest
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.server == true
      resources:
        limits:
            memory: 512M
        reservations:
            memory: 256M
    volumes:
      - ./postgres-entrypoint:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - net

networks:
  net:
    driver: overlay
  traefik-public:
    external: true

volumes:
  back-avatars:
